#!/bin/sh

# Signing isn't deterministic due to random nonce, so it's hard to test automatically
echo -n "Signing with Lfm4QkCoHtVg952mJwJKyXDvbUrtjFLsVn (verify manually with another program)... "
./signmessage 6usRC8K8Y7dw4UqWXCf5cyibTLzTY2DttwLh1x1FQqmoUnpzrq3 'test signature'

# We can at least check that we can verify our own random signature
echo -n "Signing and then verifying... "
./verifymessage Lfm4QkCoHtVg952mJwJKyXDvbUrtjFLsVn $(./signmessage 6usRC8K8Y7dw4UqWXCf5cyibTLzTY2DttwLh1x1FQqmoUnpzrq3 'test signature') 'test signature' >/dev/null
if [ $? -eq 0 ] ; then echo "pass."; else echo "FAIL!"; fi
